const UNA_HORA_MS = 60 * 60 * 1000;

export const PAGINA_MAXIMA_TMDB = 500;

export const FILTRO_PLATAFORMAS = Object.freeze({
  RESULTADOS_OBJETIVO: 12,
  MAX_PAGINAS_POR_REQUEST: 2,
  CONCURRENCIA_TMDB: 8,
  TTL_CACHE_MS: 24 * UNA_HORA_MS,
  MAX_ENTRADAS_CACHE: 5000,
});
